spring:
  application:
    name: Inventory

  datasource:
    url: jdbc:h2:mem:inventorydb
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: true

  h2:
    console:
      enabled: true

server:
  port: 8080